#!/bin/sh
cd /blacklist/list
wget -N https://antifilter.download/list/ipsum.lst https://antifilter.download/list/subnet.lst
old=$(cat /tmp/md5.txt);
new=$(cat /blacklist/list/*.lst | md5sum | head -c 32);
if [ "$old" != "$new" ]
then
cat /blacklist/list/ipsum.lst | sed 's_.*_route & reject;_' > /etc/bird/ipsum.txt
cat /blacklist/list/subnet.lst | sed 's_.*_route & reject;_' > /etc/bird/subnet.txt
/usr/sbin/birdc configure;
logger "RKN list reconfigured at $(date)";
echo $new > /tmp/md5.txt;
fi
